import os

CONFIG = {
    "openai_api_key": os.environ["OPENAI_API_KEY"], #Put your own there
    "openai_organization": os.environ["OPENAI_API_ORG"], #Put your own there (needed afaik if using gpt4)
    "INSTRUCTIONS":{"instruction_with_extracted_ontology":"""You are a task-oriented dialogue system focusing on doing Dialogue State Tracking. Using the following knowledge base as grounding for acts, slots and values, generate the belief state of the last dialogue turn in the following conversation between a USER and a SYSTEM in a task-oriented dialogue setting. The results should be in json format with 'domain', 'act' and 'belief_state' as primary keys, for example {'domain':domain, 'act':act, 'belief_state':{first slot: first value, second slot: second value, etc...}:""",
                    "instruction_with_slots":"""Generate the dialogue state of the following dialogue between a USER and a task-oriented dialogue SYSTEM. The results should be in a single python dictionary following this format: {"domain1-slot1":value1, "domain2-slot2":"value2"}. Use the provided domain and slots, and nothing else:""",
                   "instruction_with_slots_2":"""Generate the belief state of the very last dialogue turn in the following conversation between a USER and a SYSTEM in a task-oriented dialogue setting. The results should be in json format following this format: {'slot1':'value1', 'slot2':'value2', etc...}. Use the slot from SLOTS to generate the belief state:""",
                   "instruction_with_slots_recorrect":"""You are a task-oriented dialogue system focusing on doing Dialogue State Tracking. Using the following SLOTS provided, another faulty system already generated the belief state of the last dialogue turn in the following conversation between a USER and a SYSTEM in a task-oriented dialogue setting. You should generate the new and correct belief state. The results should be in json format with the slot name as the primary key, and the retrieved value associated to the slot, for example {'slot1':'value1', 'slot2':'value2', etc...}:""",
                   "instruction_with_slots_recorrect_2":"""Using the following SLOTS provided with their description, another faulty system already generated the WRONG BELIEF STATES of the last dialogue turn in the following conversation between a USER and a SYSTEM in a task-oriented dialogue setting. You should generate the new and CORRECTED BELIEF STATES. The results should be in json format following this format: {'slot1':'value1', 'slot2':'value2', etc...}.""",
                   "instruction_with_slots_recorrect_3":"""Using the following SLOTS provided, another system generated the WRONG BELIEF STATES of the last dialogue turn in the conversation between a USER and a SYSTEM given in the CONTEXT, in a task-oriented dialogue setting. You should generate the CORRECTED BELIEF STATES. The results should be in json format following this format: {'slot1':'value1', 'slot2':'value2', etc...}.""",
                   "instruction_with_slots_recorrect_4":"""A task-oriented dialogue system has generated the following belief state: {belief_state} for the following dialogue. The belief states are slightly wrong, so use the provided SLOTS to generate the corrected belief states. The results should be in json format following this format: {'slot1':'value1', 'slot2':'value2', etc...}.""",
                   "instruction_response_generation":"""In a task oriented dialogue setting, generate a SYSTEM response to the USER query in the conversation provided in CONTEXT. You should follow the information provided in ACT to generate this answer. Do not answer with anything other than what is provided in the dialogue act:""",
                   "instruction_e2e":"""Generate the answer of the SYSTEM in the following conversation between a USER and a SYSTEM in a task-oriented dialogue setting. You can either request more details to the user that is available in the knowledge base to complete the goal, or simply answer the user's request. Do not provide multiple choice for the user to choose, just recommend one, and generate nothing other that the SYSTEM reply. Use the following knowledge base to interact with the user:""",
                   "instruction_e2e_query_database":"""Suppose you have access to a database with the all necessary information, what do you need to query to the databse in order to reply to the user in the following conversation?""",
                   "instruction_e2e_rg":"""In a task oriented dialogue setting, generate a natural and helpful SYSTEM response to the USER query in the conversation provided in CONTEXT. You should follow the information provided in ACT to generate this answer. Do not mention that you are referring to a dataframe and don't overload the user with too many choices. You have the ability to perform confirm bookings for users:""",
                   "instruction_e2e_rg_aug":"""In a task oriented dialogue setting, generate a natural and helpful SYSTEM response to the USER query in the conversation provided in CONTEXT. You should follow the information provided in ACT to generate this answer. Do not mention that you are referring to a dataframe and don't overload the user with too many choices. Do not generate any places, addresses or additional informations that you haven't be provided with explicitly. Instead, you should either follow conversation naturally and if the user seems like he wants to close the conversation, you can choose to ignore the act and close the conversation as well. You have the ability to perform confirm bookings for users:""",
                   }, 
    "PROMPT_TEMPLATES":{"template_with_extracted_ontology":{"template": """{instruction}\n\nKNOWLEDGE BASE:\n{ontology}\n\nCONTEXT:\n{dialogue_context}""",
                                                           "input_variables": ["instruction", "ontology", "dialogue_context"]},
                       "template_with_slots":{"template": """{instruction}\n\nSLOTS:\n{slots}\n\nYou can follow this example:\n{example}\n\n{dialogue_context}BELIEF STATE:""",
                                                           "input_variables": ["instruction", "slots", "example", "dialogue_context"]},
                       "template_with_slots_recorrect":{"template": """{instruction}\n\nSLOTS:\n{slots}\n\nCONTEXT:\n{dialogue_context}\n\nWRONG BELIEF STATES:\n{belief_states}\n\nCORRECT BELIEF STATES:""",
                                                        "input_variables": ["instruction", "slots", "dialogue_context", "belief_states"]},
                       "template_with_slots_recorrect_4":{"template": """{instruction}\n\nSLOTS:\n{slots}\n\nCONTEXT:\n{dialogue_context}\n\n""",
                                                        "input_variables": ["instruction", "slots", "dialogue_context"]},
                       "template_query_database":{"template": """{instruction}\n\nBELIEF STATES:\n{belief_states}\n\nSELECT * FROM""",
                                                           "input_variables": ["instruction", "belief_states"]},
                       "template_response_generation":{"template": """{instruction}\n\nYou can follow this example:\n{example}\n\nCONTEXT:\n{dialogue_context}""",
                                                           "input_variables": ["instruction", "example", "dialogue_context"]},
                        "template_e2e":{"template": """{instruction}\n\n{database}\n\n{dialogue_context}""",
                                        "input_variables":["instruction", "database", "dialogue_context"]},
                        "template_e2e_query_database":{"template":"""{instruction}\nINFORMATION: address, area, name, phone, postcode, pricerange, entrance fee, food, internet, parking, stars, arriveby, day, departure, destination, leaveat, price.\n\nYou can follow these examples:{example}\n\n{dialogue_context}\n\nNeed:""",
                                                       "input_variables":["instruction", "example", "dialogue_context"]},
                        "template_e2e_rg":{"template":"""{instruction}\n\nCONTEXT:\nYou can follow this example:{example}\n\nCONTEXT:\n{dialogue_context}\n\nACT:{dialogue_act}\n\nSYSTEM:""",
                                           "input_variables":["instruction", "example", "dialogue_context", "dialogue_act"]},
                      },
    "EXAMPLES":{"dst_dh-1":"""USER: I need a cheap hotel with internet in the west of town\nSYSTEM: Sure, anything else?\nUSER: Yes, I am looking with for italian food around the same area\nBELIEF STATE: {"hotel-pricerange":"cheap,"hotel-internet":"yes", "hotel-area":"west", "restaurant-food":"italian", "restaurant-area":"west"}""",
                "dst_dh0":"""USER: I need a cheap hotel with internet in the west of town\nBELIEF STATE: {"hotel-pricerange":"cheap,"hotel-internet":"yes", "hotel-area":"west"}""",
                "response_generation":"""USER: How much does the banana cost?\nACT: Inform the user that the price is 10$, the promotion is 80%, and the choice is 5, and request the amount that user wants.\nSYSTEM: There are 5 to choose from. Banana currently cost 10$, with a 80% off. How many would you like?""",
                "e2e_query_database":"""USER: I need fruits.\nSYSTEM: Do you have any preferences?\nUSER: Yes, apples if possible. How expensive and how many are there?\n\nNeed: Information about pricerange and and count for apple\n\nUSER: Cool, that asnwers my question.\nSYSTEM: I am happy to help. Anything else needed?\nUSER: I'm done, thanks!\n\nNeed: Information about nothing\n\nUSER: I'm looking for a popular zoo around here\nSYSTEM: There are multiple zoos I can recommend. Any preference on the location?\nUSER: I want it to be in the west part of town\n\nNeed: Information about zoo in the west""",
                "e2e_response_generation":"""USER: I need a place to fish\nSYSTEM: Any preference in the type of fish?\nUSER: Preferably salmons, but sardines are also fine\n\nACT: blue lake, 37th avenue\n\nSYSTEM: How about blue lake, 37th avenue in that case?"""},
    "multiwoz21":{
                "requestable_slots" : {"taxi": ["car", "phone"],
                                    "police": ["postcode", "address", "phone"],
                                    "hospital": ["address", "phone", "postcode"],
                                    "hotel": ["address", "postcode", "type", "internet", "phone", "parking", "pricerange", "stars", "area", "reference"],
                                    "attraction": ["price", "address", "type", "postcode", "phone", "area", "reference"],
                                    "train": ["time", "leaveat", "price", "arriveby", "id", "reference"],
                                    "restaurant": ["phone", "postcode", "address", "pricerange", "food", "area", "reference"]
                                    },
                "informable_slots" : {"taxi": ["leaveat", "destination", "departure", "arriveby"],
                                    "police": [],
                                    "hospital": ["department"],
                                    "hotel": ["parking", "pricerange", "type", "internet", "stay", "day", "people", "area", "stars", "name"],
                                    "attraction": ["area", "type", "name"],
                                    "train": ["destination", "day", "arriveby", "departure", "people", "leaveat"],
                                    "restaurant": ["food", "pricerange", "area", "name", "time", "day", "people"]
                                    },
                "all_requestable_slots":["car", "address", "postcode", "phone", "type", "internet",  "parking", "pricerange", "food",
                                "stars", "area", "reference", "time", "leaveat", "price", "arriveby", "id"],
                "all_informable_slots":["parking", "pricerange", "internet", "stay", "type", "day", "people", "area", "stars", "name",
                                "leaveat", "destination", "departure", "arriveby", "food", "time"],
                }
}